### ISSUE TITLE
why is this a compent instead of a mixin?

### ISSUE THREAD

**Issue by Pomax** [JedWatson/react-hammerjs#12]
This would be far more valuable as a mixin, so you can use it with arbitrary components, instead of having to wrap them in a component.

**Comment by deiucanta** [comment]
I agree.

**Comment by JedWatson** [comment]
I'm happy to add Mixin support, we did it for [react-tappable](https://github.com/jedwatson/react-tappable) and it's been a good solution there. Would love a PR that implements the same technique, or I'll get to it when I've got some time.

**Comment by JedWatson** [comment]
Closed by #19
