### ISSUE TITLE
Doesn't work when used with server side rendering

### ISSUE THREAD

**Issue by talkhot** [JedWatson/react-hammerjs#14]
Hammerjs troughs 'ReferenceError: window is not defined' when rendering React on the server. The problem seems to lie in the hammer.js wrapper.
```javascript
react-hammerjs/node_modules/hammerjs/hammer.js:2463
})(window, document, 'Hammer');
ReferenceError: window is not defined
```
I use this as a quick fix in Hammer.js, but doubt if this is the right solution for this?
```javascript
if (typeof window !== 'undefined') {
  var  Hammer = require('hammerjs');
}
```

**Comment by neeboo** [comment]
I also have the same problem when using browserify

**Comment by JedWatson** [comment]
@talkhot that's actually a totally fine workaround, I've added it and published a new version with the fix. Thanks!

**Comment by wlingke** [comment]
@JedWatson is it possible to check for more than just `window` - for example maybe `document` as well? I have a large app where we stub `window = {}` for server side rendering.
