### ISSUE TITLE
onPinchEnd support

### ISSUE THREAD

**Issue by marcovdijk** [JedWatson/react-hammerjs#26]
Great work on this! Can you please also add PinchEnd support? I'm not a Git user so I can't contribute myself.

**Comment by maxfrigge** [comment]
Agree. The pinch start event is rather important too. Would be really nice to have all the hammer events supported actually :)

**Comment by maxfrigge** [comment]
Has this been resolved?

**Comment by bramus** [comment]
This was added in commit f8e6afab5817b3f2a99bbc115fa1d7d737f99063. This issue can be closed.
