### ISSUE TITLE
onTap vs onTouchStart

### ISSUE THREAD

**Issue by revolunet** [JedWatson/react-hammerjs#3]
Hi,

i was wondering if there is any difference between onTap and the builtin React onTouchStart ?

**Comment by JedWatson** [comment]
Yes - onTap uses hammer.js to detect "taps" - which are distinct from TouchStarts (which could be scrolling, etc) and "presses".

**Comment by JedWatson** [comment]
I'd also recommend checking out my react-tappable library if you're interested in this: https://github.com/JedWatson/react-tappable
