### ISSUE TITLE
Support for swipe left|right?

### ISSUE THREAD

**Issue by sebastialonso** [JedWatson/react-hammerjs#31]
This is a fairly good component. Thank you very much!

I was wondering, how would I go if I wanted to implement onSwipeLeft for this component?

**Comment by mibamur** [comment]
+1

**Comment by bramus** [comment]
By looking at the code `react-hammerjs` only supports listening to the entire `onSwipe` event, and not individual `onSwipeLeft`, `onSwipeRight`, `onSwipeUp`, and `onSwipeDown` events.

To get to know the direction of a swipe, do this: in your `onSwipe` event handler compare `event.direction` to one of the `Hammer.DIRECTION_*` contstants. See http://hammerjs.github.io/api/#constants for a full list of constants.

**Comment by zhangchao828** [comment]
you should provide the prop vertical={true},then you will know the direction of a swipe by e.deltaX or e.deltaY

**Comment by JedWatson** [comment]
Fixed by #51
