### ISSUE TITLE
swipe left/right

### ISSUE THREAD

**Issue by chrisjbrown** [JedWatson/react-hammerjs#33]
how do you set recognizers for onSwipe?

this isn't working for detecting swiperight

`let options = {
            recognizers: {
                swipe: {
                    event: 'swiperight'
                }
            }
        };`

**Comment by bramus** [comment]
By looking at the code `react-hammerjs` only supports listening to the entire `onSwipe` event, and not individual `onSwipeLeft`, `onSwipeRight`, `onSwipeUp`, and `onSwipeDown` events.

To get to know the direction of a swipe, do this: in your `onSwipe` event handler compare `event.direction` to one of the `Hammer.DIRECTION_*` contstants. See http://hammerjs.github.io/api/#constants for a full list of constants.

**Comment by jaredmharris** [comment]
Can the forked commit be added? I need to be able to call different methods based on the swipe direction. Not sure how to do that with the current implementation.

**Comment by JedWatson** [comment]
Fixed by #51
