### ISSUE TITLE
Expose Hammer constants

### ISSUE THREAD

**Issue by kamilmielnikcodete** [JedWatson/react-hammerjs#34]
Since Hammer object is not exposed it's impossible to use [constants](http://hammerjs.github.io/api/#constants) defined on it (without using a hack).

**Comment by bramus** [comment]
It's exposed on `window`, not? E.g. using `Hammer.DIRECTION_LEFT` works just fine.

**Comment by kamilmielnikcodete** [comment]
Yes, right.
I was not aware that hammerjs pollutes global scope.

Thank you.
