### ISSUE TITLE
Warning property

### ISSUE THREAD

**Issue by ChocoMomo** [JedWatson/react-hammerjs#45]
I am getting a warning message when using the hammer component:

`Warning: Unknown prop `options` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

**Comment by mdjasper** [comment]
Should be fixed with this Pull Request. Hopefully it is merged quickly :) https://github.com/JedWatson/react-hammerjs/pull/47

**Comment by mdjasper** [comment]
@JedWatson Thanks for merging the PR for this bugfix (#47). Would you mind publishing that change to NPM as well?

**Comment by JedWatson** [comment]
@mdjasper it was published to npm with version `0.5.0`
