### ISSUE TITLE
Conflicting versions of React, package.json suggestions

### ISSUE THREAD

**Issue by irae** [JedWatson/react-hammerjs#6]
Hi there,

I am using React 0.13 beta on a small project and when I tried to pull react-hammer in, I had conflicting problems since I am using CommonJS with browserify and this allowed react-hammer to still use React 0.12 although my project is in 0.13. The end result is a mess of warnings and weird exceptions.

As far as I know, the best way to solve this is to move react on package.json from `dependencies` to `peerDependencies` and also making sure the supported versions are correct. So far, react-hammer is 100% compatible with react 0.13 as far as I tested.

If anyone else is having this problem, one workaround is to require the dist version directly. Here is how I am requiring react-hammer right now:

    var Hammer = require('react-hammerjs/dist/react-hammerjs');

The drawback for this workaround is this will only work when React is global, which works for me since I already have ` --insert-global-vars React` on my browserify configuration.

**Comment by JedWatson** [comment]
Hi, and apologies for the delayed response.

I've implemented an alternative solution to this, see #7 

I've also published it as a new version `v0.1.4`, please let me know if that solves the problem for you.
