### ISSUE TITLE
one hammer trigger another hammer

### ISSUE THREAD

**Issue by githubtuxedo** [JedWatson/react-hammerjs#75]
when i use react-hammerjs to build a single page web application, I found that when I wrote Hammer with props 'onTap' and and another Hammer  behind. The second Hammer tirggered when I clicked the first Hammer , How can I prevent it, Thanks for every advice.

**Comment by githubtuxedo** [comment]
And they are not parent and son. totally different part. Just shown by different condition, so i think it's not about bubble up

**Comment by githubtuxedo** [comment]
Besides, component A with Hammer, component B Input with onFocus behind would be activated by tap top Hammer component.

**Comment by mengxxSELF** [comment]
How do you use it?  I created multiple instances. None of them affect each other

**Comment by mengxxSELF** [comment]
How do you use it? ~ I created multiple instances. None of them affect each other

**Comment by githubtuxedo** [comment]
Forgot close
