### ISSUE TITLE
Use of deprecated React.PropTypes breaks in React v16

### ISSUE THREAD

**Issue by flut1** [JedWatson/react-hammerjs#80]
The Hammer component references `React.PropTypes.string`. However, accessing PropTypes from the `react` package is now deprecated and will break in React v16. Instead, PropTypes should be imported from the `prop-types` package.

**Comment by flut1** [comment]
Related #79

**Comment by flut1** [comment]
This is a duplicate of #74, my apologies.

**Comment by Redmega** [comment]
Fixed by #78

**Comment by JedWatson** [comment]
Fixed as of `1.0.1`
